# Generated by Django 4.2.13 on 2024-05-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_bio_user_city_user_country_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Phone number'),
        ),
    ]
