# Generated by Django 4.2.13 on 2024-05-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image_alter_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='media/products/default.jpg', null=True, upload_to='products/'),
        ),
    ]
