# Generated by Django 4.2.13 on 2024-05-29 19:50

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_rendered',
            field=markdownfield.models.RenderedMarkdownField(default='test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=markdownfield.models.MarkdownField(rendered_field='description_rendered'),
        ),
    ]
