# Generated by Django 4.2.13 on 2024-05-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_description_rendered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='heading',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
