# Generated by Django 4.2.13 on 2024-05-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='heading',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
